Repository newrelic/csec-java-agent, pull requests merged in 2024-01, with the labels that each got.

#146 Unit test for jersey-2
  instrumentation-security/jersey-2.16/src/test/java/com/nr/agent/security/instrumentation/jersey2/JerseyTests.java
  instrumentation-security/jersey-2.16/src/test/java/com/nr/agent/security/instrumentation/jersey2/resources/Resource.java
  instrumentation-security/jersey-2/src/test/java/com/nr/agent/security/instrumentation/jersey2/JerseyTests.java
  instrumentation-security/jersey-2/src/test/java/com/nr/agent/security/instrumentation/jersey2/resources/Resource.java
Labels: Unit test

#145 Unit tests for jersey-3
  instrumentation-security/jersey-3/src/test/java/com/nr/agent/security/instrumentation/jersey2/JerseyTests.java
  instrumentation-security/jersey-3/src/test/java/com/nr/agent/security/instrumentation/jersey2/resources/Resource.java
Labels: Unit test

#144 Instrumentation support for mule-3.6
  instrumentation-security/mule-3.6/build.gradle
  instrumentation-security/mule-3.6/src/main/java/com/newrelic/agent/security/instrumentation/mule36/MuleHelper.java
  instrumentation-security/mule-3.6/src/main/java/org/mule/module/http/internal/listener/HttpRequestToMuleEvent_Instrumentation.java
  instrumentation-security/mule-3.6/src/main/java/org/mule/module/http/internal/listener/async/RequestHandler_Instrumentation.java
  instrumentation-security/mule-3.6/src/main/java/org/mule/module/http/internal/listener/grizzly/GrizzlyRequestDispatcherFilter_Instrumentation.java
  settings.gradle
Labels: Intrumentation

#143 Instrumentation support for mule-3.7
  instrumentation-security/mule-3.7/build.gradle
  instrumentation-security/mule-3.7/src/main/java/com/newrelic/agent/security/instrumentation/mule37/MuleHelper.java
  instrumentation-security/mule-3.7/src/main/java/org/mule/module/http/internal/listener/HttpRequestToMuleEvent_Instrumentation.java
  instrumentation-security/mule-3.7/src/main/java/org/mule/module/http/internal/listener/async/RequestHandler_Instrumentation.java
  instrumentation-security/mule-3.7/src/main/java/org/mule/module/http/internal/listener/grizzly/GrizzlyRequestDispatcherFilter_Instrumentation.java
  settings.gradle
Labels: Intrumentation

#61 gRPC 1.40.0 instrumentation
  instrumentation-security/grpc-1.40.0/build.gradle
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/GrpcClientUtils.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/GrpcServerUtils.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/GrpcUtils.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/ProtoMessageToMap.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/client/GrpcClient.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/client/GrpcStubs.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/CustomFutureTask.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/EventAbortPolicy.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/GrpcRequestProcessor.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/GrpcRequestThreadPool.java
  instrumentation-security/grpc-1.40.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc1400/processor/MonitorGrpcRequestQueueThread.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/Channel_Instrumentation.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/ClientCall_Instrumentation.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/ServerCallListener_Instrumentation.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/internal/ServerCallImpl_Instrumentation.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/internal/ServerImpl_Instrumentation.java
  instrumentation-security/grpc-1.40.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
  newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/MonitorGrpcFuzzFailRequestQueueThread.java
  newrelic-security-agent/src/main/java/com/newrelic/agent/security/instrumentator/httpclient/RestRequestProcessor.java
  settings.gradle
Labels: Intrumentation

#63 gRPC 1.4.0 instrumentation
  instrumentation-security/grpc-1.4.0/build.gradle
  instrumentation-security/grpc-1.4.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc140/GrpcClientUtils.java
  instrumentation-security/grpc-1.4.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc140/GrpcServerUtils.java
  instrumentation-security/grpc-1.4.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc140/GrpcUtils.java
  instrumentation-security/grpc-1.4.0/src/main/java/com/newrelic/agent/security/instrumentation/grpc140/ProtoMessageToMap.java
  instrumentation-security/grpc-1.4.0/src/main/java/io/grpc/Channel_Instrumentation.java
  instrumentation-security/grpc-1.4.0/src/main/java/io/grpc/ClientCall_Instrumentation.java
  instrumentation-security/grpc-1.4.0/src/main/java/io/grpc/ServerCallListener_Instrumentation.java
  instrumentation-security/grpc-1.4.0/src/main/java/io/grpc/internal/ServerCallImpl_Instrumentation.java
  instrumentation-security/grpc-1.4.0/src/main/java/io/grpc/internal/ServerImpl_Instrumentation.java
Labels: Intrumentation

#65 Unit test cases of gRPC 1.40.0
  instrumentation-security/grpc-1.40.0/src/test/java/com/nr/agent/security/instrumentation/grpc1400/GrpcTest.java
  instrumentation-security/grpc-1.40.0/src/test/java/com/nr/agent/security/instrumentation/grpc1400/app/TestClient.java
  instrumentation-security/grpc-1.40.0/src/test/java/com/nr/agent/security/instrumentation/grpc1400/app/TestServer.java
  instrumentation-security/grpc-1.40.0/src/test/proto/hello_streaming.proto
  instrumentation-security/grpc-1.40.0/src/test/proto/helloworld.proto
  instrumentation-security/grpc-1.40.0/src/test/resources/no_grpc_errors.yml
Labels: Unit test

#66 Unit test cases of gRPC 1.22.0
  instrumentation-security/grpc-1.22.0/src/test/java/com/nr/agent/security/instrumentation/grpc1220/GrpcTest.java
  instrumentation-security/grpc-1.22.0/src/test/java/com/nr/agent/security/instrumentation/grpc1220/app/TestClient.java
  instrumentation-security/grpc-1.22.0/src/test/java/com/nr/agent/security/instrumentation/grpc1220/app/TestServer.java
  instrumentation-security/grpc-1.22.0/src/test/proto/hello_streaming.proto
  instrumentation-security/grpc-1.22.0/src/test/proto/helloworld.proto
  instrumentation-security/grpc-1.22.0/src/test/resources/no_grpc_errors.yml
Labels: Unit test

#67 Unit test cases of gRPC 1.4.0
  instrumentation-security/grpc-1.4.0/src/test/java/com/nr/agent/security/instrumentation/grpc140/GrpcTest.java
  instrumentation-security/grpc-1.4.0/src/test/java/com/nr/agent/security/instrumentation/grpc140/app/TestClient.java
  instrumentation-security/grpc-1.4.0/src/test/java/com/nr/agent/security/instrumentation/grpc140/app/TestServer.java
  instrumentation-security/grpc-1.4.0/src/test/proto/hello_streaming.proto
  instrumentation-security/grpc-1.4.0/src/test/proto/helloworld.proto
  instrumentation-security/grpc-1.4.0/src/test/resources/no_grpc_errors.yml
Labels: Unit test

#165 NR-216080: Fix for Null Pointer Exception in stack trace processing
  newrelic-security-agent/src/main/java/com/newrelic/api/agent/security/Agent.java
Labels: bug

#169 NR-216474: fix for Null Pointer exception for FILE_OPERATION
  newrelic-security-api/src/main/java/com/newrelic/api/agent/security/instrumentation/helpers/ServletHelper.java
Labels: bug
